plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common-libs:common-domain')
    implementation project(':common-libs:common-security')
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    runtimeOnly 'org.postgresql:postgresql'
}
